# Generated by Django 4.2.7 on 2024-03-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='data',
            new_name='date',
        ),
    ]
