# Generated by Django 4.2.7 on 2024-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_data_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
