# Generated by Django 4.2.7 on 2024-03-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
